contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #ahe channel"
    url: https://nfcore.slack.com/channels/ahe
    about: Discussion about the nf-core/ahe pipeline
